name = input("enter your name")
surname = input("enter your surname")
age = input("enter your age")
weight = input("enter your weight")
height = input("enter your height")
print("name:"+name)
print("surname:"+surname)
print("age:"+age)
print("weight:"+weight)
print("height:"+height)